### ISSUE TITLE
glGetString / glViewport not available.

### ISSUE THREAD

**Issue by maeln** [stephanh42/RacketGL#16]
When trying to run any test in tests/opengl, the viewer window is displayed but nothing is drawn in it and the following messages are produced in stderr :

```
OpenGL procedure not available: glGetString
viewer.rkt:22:9: OpenGL procedure not available: glViewport
```

Image of the viewer with the output :
![Bug](https://maeln.com/img/bug.png)

The configuration is the following: Windows 10, Nvidia GTX1070 with driver 376.53, Racket 6.8, fresh install of the package opengl.

**Comment by stephanh42** [comment]
Hi Maël,

I think your driver may only support the OpenGL "core" profile and
therefore lacks glGetString. (Possibly this is even configurable?)

Unfortunately the demos rely on this function at the moment.

Stephan


Op 21 apr. 2017 6:05 p.m. schreef "Maël Naccache" <notifications@github.com
>:

When trying to run any test in tests/opengl, the viewer window is displayed
but nothing is drawn in it and the following messages are produced in
stderr :

OpenGL procedure not available: glGetString
viewer.rkt:22:9: OpenGL procedure not available: glViewport

Image of the viewer with the output :
[image: Bug]
<https://camo.githubusercontent.com/04a569cdc493fa243e808dcb08ceed0231fde876/68747470733a2f2f6d61656c6e2e636f6d2f696d672f6275672e706e67>

The configuration is the following: Windows 10, Nvidia GTX1070 with driver
376.53, Racket 6.8, fresh install of the package opengl.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/stephanh42/RacketGL/issues/16>, or mute the thread

**Comment by maeln** [comment]
I tested on my Ubuntu session on the same machine with the nvidia proprietary drivers and it works fine.
So it's definitely a driver / windows issue. I will see if I can find more info.

**Comment by maeln** [comment]
Yes, it seems to be related to NVidia's drivers : https://devtalk.nvidia.com/default/topic/949938/api-usage-unsupported-glgetintegerv-glgetstring-glclear/
