### ISSUE TITLE
Wrong type in glUniform1f.

### ISSUE THREAD

**Issue by maeln** [stephanh42/RacketGL#17]
The [glUniform1f](https://docs.racket-lang.org/opengl/glU___.html#%28def._%28%28lib._opengl%2Fmain..rkt%29._gl.Uniform1f%29%29) expect a GLFoat ( see [OpenGL documentation](https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glUniform.xml) ) which is a float (32bits IEEE-754 floating-point value) which correspond to a [single-flonum](https://docs.racket-lang.org/reference/number-types.html#%28def._%28%28quote._~23~25kernel%29._single-flonum~3f%29%29) in Racket but in the type asked is a [flonum](https://docs.racket-lang.org/reference/number-types.html#%28def._%28%28quote._~23~25kernel%29._flonum~3f%29%29) which is a double.

**Comment by stephanh42** [comment]
Hi Maël,

The wrapper converts the flonum to a c float internally.

Stephan

Op 22 apr. 2017 20:56 schreef "Maël Naccache" <notifications@github.com>:

The glUniform1f
<https://docs.racket-lang.org/opengl/glU___.html#%28def._%28%28lib._opengl%2Fmain..rkt%29._gl.Uniform1f%29%29>
expect a GLFoat ( see OpenGL documentation
<https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glUniform.xml>
) which is a float (32bits IEEE-754 floating-point value) which correspond
to a single-flonum
<https://docs.racket-lang.org/reference/number-types.html#%28def._%28%28quote._%7E23%7E25kernel%29._single-flonum%7E3f%29%29>
in Racket but in the type asked is a flonum
<https://docs.racket-lang.org/reference/number-types.html#%28def._%28%28quote._%7E23%7E25kernel%29._flonum%7E3f%29%29>
which is a double.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/stephanh42/RacketGL/issues/17>, or mute the thread

**Comment by maeln** [comment]
I made a fork were I changed the conversion of _float to single-flonum? instead of flonum?. I will try to see if that fixes it without creating bugs.

**Comment by stephanh42** [comment]
I don't see a bug here. The function already accepts single-flonum's, these
are included in the flonum type.

It is just more convenient to also allow double-flonum's here since these
are the default in Racket.

Stephan

Op 22 apr. 2017 21:04 schreef "Maël Naccache" <notifications@github.com>:

**Comment by maeln** [comment]
My bad, flonum? works fine has you said. I was confused because (flonum? (real->single-flonum? 0.0)) return #f and I thought that passing a flonum? was truncating the value because my shader wasn't computing properly when passing (current-inexact-milliseconds) via glUniform1f.
